//
// Created by quinc on 03/10/2023.
//

#ifndef PROYECTO_RENDIMIENTO_ARQUITECTURA_GRID_H
#define PROYECTO_RENDIMIENTO_ARQUITECTURA_GRID_H


class grid {

};


#endif //PROYECTO_RENDIMIENTO_ARQUITECTURA_GRID_H
