//
// Created by quinc on 03/10/2023.
//

#ifndef PROYECTO_RENDIMIENTO_ARQUITECTURA_PROGARGS_H
#define PROYECTO_RENDIMIENTO_ARQUITECTURA_PROGARGS_H


class progargs {

};


#endif //PROYECTO_RENDIMIENTO_ARQUITECTURA_PROGARGS_H
